### ISSUE TITLE
please make NameOfImpl public

### ISSUE THREAD

**Issue by benhutchison** [dwickern/scala-nameof#2]
`NameOfImpl` is currently declared private. This has the effect of preventing users (ie me) from aliasing the `nameOf` macro to something more appropriate for their context.

I'd like to use the following in a DSL:
```scala
def ref(expr: Any): String = macro NameOfImpl.nameOf
```

Example of same pattern from SBT:
https://github.com/sbt/sbt/blob/9ee8299383afb8c64f175acd9d3cb8648be519b6/sbt/src/main/scala/package.scala#L46

**Comment by dwickern** [comment]
Interesting, I hadn't thought about that use-case. Sure, I'll make NameOfImpl a public API

**Comment by benhutchison** [comment]
thanks :)
