### ISSUE TITLE
anonymous types support, i.e.: `new js.Object {}`

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [dwickern/scala-nameof#3]
how can `nameOf` be made to work for anonymous `new js.Object{}`:
```
val mutations = new js.Object {
    def increment(state: State) = state.count+=1
    def decrement(state: State) = state.count-=1
}

// Error: " value increment is not a member of scala.scalajs.js.Object"

val name = nameOf(mutations.increment _) 
```

**Comment by Andrei-Pozolotin** [comment]
this is a work around, but rather verbose:
```
  @ScalaJSDefined
  trait Mutations extends js.Object {
    def increment(state: State)
    def decrement(state: State)
  }

  val mutations = new Mutations {
    def increment(state: State) = state.count+=1
    def decrement(state: State) = state.count-=1
  }

// works fine:

val name = nameOf(mutations.increment _) 
```

**Comment by dwickern** [comment]
Am I correct that this is scalajs specific? It works with `java.lang.Object` in place of `js.Object`

**Comment by Andrei-Pozolotin** [comment]
yes, there are bunch of restrictions
https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html

**Comment by dwickern** [comment]
From looking at https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html#caveat-with-reflective-calls it seems this behavior is intended. I don't think there is anything we can do
